name:                imageCompStack
version:             0.1.0.0
github:              "Aubi0ne/imageCompStack"
license:             BSD3
author:              "Benjamin FABRE"
maintainer:          "benjamin.fabre@epitech.eu"
copyright:           "2020 Benjamin FABRE"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Aubi0ne/imageCompStack#readme>

dependencies:
- base >= 4.7 && < 5
- random
- parallel

library:
  source-dirs: src

executables:
  imageCompStack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imageCompStack

tests:
  imageCompStack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - imageCompStack
